### ISSUE TITLE
#1 Provide a database structure for setup.

### ISSUE THREAD

**Issue by Libbna** [Libbna/BLOG_php_mysql_qed42#1]

**Comment by JayKandari** [comment]
![image](https://user-images.githubusercontent.com/1266231/130559742-d0e72a5c-a5d0-47cb-9d0b-5e5dea49e4a5.png)
Yes. Initial database setup is required. cannot proceed with setting up this on local.

**Comment by Libbna** [comment]
Database structure for setup has been provided in a README.md.
